### ISSUE TITLE
Lautstärke-Peak beim Deaktivieren eines Radios

### ISSUE THREAD

**Issue by assiprinz** [Mattyzero/krtcomms#1]
Ich lass das mal hier:

Wenn ich ein Radio deaktiviere, erhöht sich kurz die Lautstärke. Das kann bei empfindlichen Ohren zu unerwünschten Effekten führen.

Reproduzieren:

1. KRTComms installieren
2. Einen Radiokanal auf Palladium Radio einstellen
3. Radio Lautstärke auf .1f einstellen
4. Radio mit der Checkbox deaktivieren

-> Radio wird erst sehr laut, und wird dann deaktiviert. Merkt man bei Sprachchannels wahrscheinlich nicht so sehr, wenn gerade keiner spricht.

-> Es scheint eine Art Fadeout auf dem Soundkanal stattzufinden, dieser fade out wird offensichtlich immer von 1f auf 0f ausgeführt, und nicht wie erwartet von "$currentVolume" auf 0f

**Comment by Mattyzero** [comment]
Is in 0.1.9 gefixt
